version: "1"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    ports:
      - "80:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true
    stdin_open: true
    tty: true


